version: "3.3"
# https://docs.joinpeertube.org/install-docker
services:
  peertube:
    image: chocobozzz/peertube:production-bullseye
    env_file:
      - .env
    ports:
     - "9000:9000"
    restart: "always"
    depends_on:
      - redis
  redis:
    image: redis:6-alpine
    volumes:
      - ./docker-volume/redis:/data
    restart: "always"

