AWSTemplateFormatVersion: 2010-09-09
Parameters:
  DBUsername:
    NoEcho: "true"
    Description: Username for MySQL database access
    Type: String
    MinLength: "1"
    MaxLength: "16"
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.
  DBPassword:
    NoEcho: "true"
    Description: Password for MySQL database access
    Type: String
    MinLength: "8"
    MaxLength: "41"
    ConstraintDescription: must contain only alphanumeric characters.
Resources:
  # EFS
  FileSystem:
    Type: AWS::EFS::FileSystem
    Properties:
      Encrypted: true
      BackupPolicy:
        Status: ENABLED

  # RDS
  RDSCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      MasterUsername: !Ref DBUsername
      MasterUserPassword: !Ref DBPassword
      DatabaseName: thevideo
      Engine: aurora
      EngineMode: serverless
      StorageEncrypted: true
      ScalingConfiguration:
        AutoPause: true
        MaxCapacity: 2
        MinCapacity: 1
        SecondsUntilAutoPause: 300
      DBSubnetGroupName: !Ref DBSubnetGroup
      VpcSecurityGroupIds:
        - !Ref DBSecurityGroup

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: TheVideo Database Security Group
      VpcId: !ImportValue Core-Vpc

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: TheVideo DB Subnet Group
      DBSubnetGroupName: the-video-db-subnet-group
      SubnetIds:
        - !Ref DBSubnet1
        - !Ref DBSubnet2
  DBSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue Core-Vpc
      CidrBlock: 10.0.9.0/28
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select
        - 0
        - !GetAZs
          Ref: "AWS::Region"
  DBSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !ImportValue Core-Vpc
      CidrBlock: 10.0.9.16/28
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select
        - 1
        - !GetAZs
          Ref: "AWS::Region"

Outputs:
  FileSystemID:
    Value: !Ref FileSystem
    Export:
      Name: TheVideo-EfsId
  FileSystemArn:
    Value: !GetAtt FileSystem.Arn
    Export:
      Name: TheVideo-EfsArn
  DBSecurityGroup:
    Value: !GetAtt DBSecurityGroup.GroupId
    Export:
      Name: TheVideo-DbSecurityGroup
